index:
    path: /
    #controller: App\Controller\DefaultController::index
    controller: App\Controller\DashboardController::view
dashboard.index:
    path: /dashboard
    controller: App\Controller\DashboardController::view
home:
    path: /dashboard
    controller: App\Controller\DashboardController::view
    
login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
    
login_check:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
history.index:
    path: /dashboard
    controller: App\Controller\DashboardController::view
operation.index:
    path: /dashboard
    controller: App\Controller\DashboardController::view

transactions_init:
    path:     /transactions/{id}/{number}
    controller: App\Controller\TransactionsController::init
    methods:  [GET]
    requirements:
            id: '\d+'

transactions_view:
    path:     /transactions/view/{id}
    controller: App\Controller\TransactionsController::view
    methods:  [GET]
transactions_create:
    path:     /transactions
    controller: App\Controller\TransactionsController::createAction
    methods:  [POST]



