index:
    path: /
    #controller: App\Controller\DefaultController::index
    controller: App\Controller\DashboardController::view
dashboard.index:
    path: /dashboard
    controller: App\Controller\DashboardController::view
home:
    path: /dashboard
    controller: App\Controller\DashboardController::view
    
login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
action:
    path: /action
    controller: App\Controller\ActivationController::activatedAction
    methods: GET
login_check:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: GET|POST
activate:
    path: /activate/{id}/{token}
    controller: App\Controller\ActivationController::activate
    methods: GET
activation:
    path: /activation/{user_id}/{email}
    controller: App\Controller\ActivationController::activation
    methods: GET
viewUser:
    path: /user_view/{id}
    controller: App\Controller\ActivationController::viewUser
    methods: GET
activated:
    path: /activated
    controller: App\Controller\ActivationController::activatedAction
    methods: GET
verify:
    path: /verify
    controller: App\Controller\ActivationController::verify
    methods: POST
request_reset:
    path: /request_reset
    controller: App\Controller\PasswordController::requestReset
    methods: GET
request_true:
    path: /request_true/{operation?}
    controller: App\Controller\PasswordController::requestTrue
    methods: GET|POST
send_sms:
    path: /send_activation_token/{type}/{id}
    controller: App\Controller\ActivationController::send_activation_token
    methods: GET
retrieve_account:
    path: /accounts/{id}/retrieve
    controller: App\Controller\AccountController::retrieve
    methods: GET
list_accounts:
    path: /accounts/{id}/list_accounts
    controller: App\Controller\AccountController::listAccounts
    methods: GET
list_accounts_types:
    path: /accounts/listAccountsTypes
    controller: App\Controller\AccountController::listAccountsTypes
    methods: GET
generate_confirm_code:
    path: /accounts/generateConfirmCode/{id}
    controller: App\Controller\AccountController::generateConfirmCode
    methods: GET
estimate:
    path: /accounts/estimate
    controller: App\Controller\AccountController::estimate
    methods: GET
create_account:
    path: /create_account
    controller: App\Controller\AccountController::createAccount
    methods: POST
set_trusted_hosts_list:
    path: /set_trusted_hosts_list
    controller: App\Controller\AccountController::setTrustedHostsList
    methods: POST
renew_security_token:
    path: /renew_security_token
    controller: App\Controller\AccountController::renewSecurityToken
    methods: POST
promote:
    path: /promote_account
    controller: App\Controller\AccountController::promoteAccount
    methods: POST
delete_account:
    path: /delete_account/{id}
    controller: App\Controller\AccountController::deleteAccount
    methods: GET
edit_account:
    path: /edit_account
    controller: App\Controller\AccountController::editAccount
    methods: POST
history:
    path: /history
    controller: App\Controller\DashboardController::viewHistory
operation.index:
    path: /operation
    controller: App\Controller\DatiTransactionController::start
pricing:
    path: /pricing
    controller: App\Controller\DatiTransactionController::getPricing
convert:
    path: /convert
    controller: App\Controller\DatiTransactionController::convert
#transactions_init:
#    path:     /transactions/{id}/{number}
#    controller: App\Controller\DatiTransactionController::start
#    methods:  [GET]
#    requirements:
#            id: '\d+'

transactions_view:
    path:     /transactions/{id?}
    controller: App\Controller\DatiTransactionController::view
    methods:  [GET]
transactions_view_local:
    path:     /transaction/local/{id}
    controller: App\Controller\DatiTransactionController::viewLocal
    methods:  [GET]
transactions_create_local:
    path:     /transaction/create_local/{id?}
    controller: App\Controller\DatiTransactionController::createLocalAction
    methods:  [GET|POST]
transactions_create:
    path:     /transactions
    controller: App\Controller\DatiTransactionController::createAction
    methods:  [POST]
#cette route est security anonymous
transactions_create_anonymous:
    path:     /send_money
    controller: App\Controller\DatiTransactionController::createAction
    methods:  [POST]
transactions_update:
    path:     /transactions/{id?}
    controller: App\Controller\DatiTransactionController::updateAction
    methods:  [PUT]
transactions_confirm:
    path:     /transactions/{id?}
    controller: App\Controller\DatiTransactionController::confirmAction
    methods:  [POST]
transaction_update_webhook:
    path:     /transaction_update_webhook
    controller: App\Controller\DatiTransactionController::updateWebhook
    methods:  [POST|GET|PUT]
main_settings:
    path:     /main_settings/{id?}
    controller: App\Controller\SettingsController::viewAction
    methods:  GET

profile_test:
    path:     /profile_testing/{id?}
    controller: App\Controller\ProfileController::testing
    methods:  GET|POST
profile_update:
    path:     /profile_update/{id?}
    controller: App\Controller\ProfileController::editAction
    methods:  GET|POST
user_refresh:
    path:     /user_refresh/{id?}
    controller: App\Controller\ProfileController::refreshUser
    methods:  GET
profile_file_upload:
    path:     /profile_file_upload/{id?}
    controller: App\Controller\ProfileController::uploadAction
    methods:  POST
profile_file_receive_test:
    path:     /file_upload
    controller: App\Controller\ProfileController::testAction
    methods:  PUT
settings:
    path:     /settings
    controller: App\Controller\SettingsController::viewAction
    methods:  GET
accounts:
    path:     /accounts
    controller: App\Controller\AccountController::viewAction
    methods:  GET
view_affiliate_account:
    path: /affiliate/accounts/{type}/view/{id}
    controller: App\Controller\AccountController::viewAffiliateAction
    methods: GET
list_affiliate_account:
    path: /affiliate/accounts/{type}/list/{id}
    controller: App\Controller\AccountController::listAffiliateAction
    methods: GET
estimate_creation_affiliate_account:
    path: /affiliate/accounts/{type}/estimate_creation
    controller: App\Controller\AccountController::estimateCreatioinAffiliateAction
    methods: GET
estimate_subscription_affiliate_account:
    path: /affiliate/accounts/{type}/estimate_subscription
    controller: App\Controller\AccountController::estimateSubscriptionAffiliateAction
    methods: GET
subscribe_affiliate_account:
    path: /affiliate/accounts/{type}/subscribe_account/{id}
    controller: App\Controller\AccountController::subscribeAffiliateAction
    methods: POST
new_affiliate_account:
    path: /affiliate/accounts/{type}/new_account
    controller: App\Controller\AccountController::newAffiliateAction
    methods: POST
edit_affiliate_account:
    path: /affiliate/accounts/{type}/edit_account/{id}
    controller: App\Controller\AccountController::editAffiliateAction
    methods: POST
delete_affiliate_account:
    path: /affiliate/accounts/{type}/delete_account/{id}
    controller: App\Controller\AccountController::deleteAffiliateAction
    methods: GET
services:
    path: /services
    controller: App\Controller\ServiceController::viewAction
    methods: GET
service_payment:
    path: /service_payments/get/{service_id}
    controller: App\Controller\ServicePaymentController::viewAction
    methods: GET
    requirements:
            id: '\d+'
service_payment_list:
    path: /service_payments/list
    controller: App\Controller\ServicePaymentController::listAction
    methods: GET
service_payment_merchant_list:
    path: /service_payments/merchant/{merchant_id}/list
    controller: App\Controller\ServicePaymentController::merchantListAction
    methods: GET
service_payment_participant_list:
    path: /service_payments/participant/list
    controller: App\Controller\ServicePaymentController::participantListAction
    methods: GET
service_payment_participant_check:
    path: /service_payments/participant/check/{service_id}
    controller: App\Controller\ServicePaymentController::participantCheckAction
    methods: GET
service_payment_create:
    path: /service_payments/create/{merchant_id}
    controller: App\Controller\ServicePaymentController::createAction
    methods: POST
service_payment_add_participant:
    path: /service_payments/participant/add/{service_id}
    controller: App\Controller\ServicePaymentController::participantAddAction
    methods: POST
service_payment_enable_participant:
    path: /service_payments/participant/enable/{service_id}/{participant_id}
    controller: App\Controller\ServicePaymentController::participantEnableAction
    methods: POST
service_payment_pay:
    path: /service_payments/pay/{service_id}
    controller: App\Controller\ServicePaymentController::payAction
    methods: POST
service_payment_history:
    path: /service_payments_history
    controller: App\Controller\ServicePaymentController::payAction
    methods: GET
service_payment_participant_login:
    path: /service_payments/participant/login/{service_id}
    controller: App\Controller\ServicePaymentController::participantLoginAction
    methods: GET
service_payment_get_history:
    path: /service_payments/history
    controller: App\Controller\ServicePaymentController::getHistoryAction
    methods: GET