index:
    path: /
    #controller: App\Controller\DefaultController::index
    controller: App\Controller\DashboardController::view
dashboard.index:
    path: /dashboard
    controller: App\Controller\DashboardController::view
home:
    path: /dashboard
    controller: App\Controller\DashboardController::view
    
login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
    
login_check:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: GET|POST
register:
    path: /register
    controller: App\Controller\RegistrationController::register
    methods: GET|POST
activate:
    path: /activate/{id}/{token}
    controller: App\Controller\ActivationController::activate
    methods: GET
activated:
    path: /activated
    controller: App\Controller\ActivationController::activatedAction
    methods: GET
send_sms:
    path: /send_sms/{id}
    controller: App\Controller\ActivationController::send_sms
    methods: GET
history.index:
    path: /dashboard
    controller: App\Controller\DashboardController::view
operation.index:
    path: /operation
    controller: App\Controller\TransactionsController::start

#transactions_init:
#    path:     /transactions/{id}/{number}
#    controller: App\Controller\TransactionsController::start
#    methods:  [GET]
#    requirements:
#            id: '\d+'

transactions_view:
    path:     /transactions/{id?}
    controller: App\Controller\TransactionsController::view
    methods:  [GET]
transactions_create:
    path:     /transactions
    controller: App\Controller\TransactionsController::createAction
    methods:  [POST]
transactions_create_anonymous:
    path:     /send_money
    controller: App\Controller\TransactionsController::createAction
    methods:  [POST]
transactions_update:
    path:     /transactions/{id?}
    controller: App\Controller\TransactionsController::updateAction
    methods:  [PUT]


